apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: backend
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
    spec:
      volumes:
        - name: local-pod-store
          persistentVolumeClaim:
            claimName: local-volume-pvc
      containers:
        - name: nginx
          image:  nginx:1.7.9
          ports:
          - name: nginx-port
            containerPort: 80
          volumeMounts:
            - name: local-pod-store
              mountPath: "/usr/share/nginx/html"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"