version: 2
jobs:
  build:
    docker:
      - image: docker:19.03
      # Setting an Environment Variables for app
        environment:
          ORG: exonet
          APP: ${ORG}/wordpress
          TAG: latest
          IMAGE_REPO: 628076641390.dkr.ecr.eu-central-1.amazonaws.com/${APP}

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory

      - setup_remote_docker:  
          version: 18.06.0-ce
          # docker_layer_caching: true 
          
      # Run a step to setup an environment variable.
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'exporting docker-image'
            docker login -u AWS --password-stdin ${AWS_SECRET_ACCESS_KEY} https://${AWS_ACCESS_KEY_ID}.dkr.ecr.us-east-1.amazonaws.com
            docker build -t ${APP}:${TAG} $CIRCLE_WORKING_DIRECTORY/docker/Dockerfile
            docker tag ${APP}:${TAG} 628076641390.dkr.ecr.eu-central-1.amazonaws.com/${ORG}:${TAG}
            docker push ${IMAGE_REPO}:${TAG}

  build_ec2:
    docker:
      - image: ansible/ansible:ubuntu1604
      # - image: ${IMAGE_REPO}:${TAG}
      #   aws_auth:
      #     aws_access_key_id: $AWS_ACCESS_KEY_ID 
      #     aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - run:
          name: Install Ansible
          command: |
            apt update -y 
            apt install -y language-pack-ja-base language-pack-ja 
            apt install -y software-properties-common 
            apt-add-repository -y ppa:ansible/ansible 
            apt update -y 
            apt install -y curl python-dev git 
            curl "https://bootstrap.pypa.io/get-pip.py" -o "/tmp/get-pip.py" 
            python /tmp/get-pip.py 
            pip install --upgrade pip && pip install --upgrade setuptools 
            pip install ansible 

      - checkout
      - run:
          name: Validate Terraform Formatting
          command: |
            cd $CIRCLE_WORKING_DIRECTORY/roles/infra/files 
            "[ -z \"$(terraform fmt -write=false)\" ] || { terraform fmt -write=false -diff; exit 1}"
          
      - run:
          name: Execute Ansible Playbook
          command: |
            cd $CIRCLE_WORKING_DIRECTORY
            ansible-playbook site.yaml --tags "create" -vvv

            