version: 2
jobs:

  build:
    docker:
      - image: hashicorp/terraform

    steps:
      - run:
          name: Install Ansible
          command: |
            apt update -y 
            apt install -y language-pack-ja-base language-pack-ja 
            apt install -y software-properties-common 
            apt-add-repository -y ppa:ansible/ansible 
            apt update -y 
            apt install -y curl python-dev git 
            curl "https://bootstrap.pypa.io/get-pip.py" -o "/tmp/get-pip.py" 
            python /tmp/get-pip.py 
            pip install --upgrade pip && pip install --upgrade setuptools 
            pip install ansible 

      - checkout
      - run:
          name: Validate Terraform Formatting
          command: |
            cd $CIRCLE_WORKING_DIRECTORY/roles/infra/files 
            "[ -z \"$(terraform fmt -write=false)\" ] || { terraform fmt -write=false -diff; exit 1}"
          
      - run:
          name: Execute Ansible Playbook
          command: |
            cd $CIRCLE_WORKING_DIRECTORY
            ansible-playbook site.yaml --tags "create" -vvv

            