#  Uncomment to install terraform
# - import_tasks: install_terraform.yml

- name: Set key path
  include_tasks: roles/common/tasks/set_vars/ssh_key_path.yml

- name: Generate terraform files
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: 0644
  with_items:
    - { src: '{{role_path}}/templates/variables.tf.j2', dest: '{{role_path}}/files/envs/prod/core/variables.tf' }
    - { src: '{{role_path}}/templates/provider.tf.j2', dest: '{{role_path}}/files/provider.tf' }
    - { src: '{{role_path}}/templates/main.tf.j2', dest: '{{role_path}}/files/main.tf' }

- name: Apply terraform files
  terraform:
    project_path: "{{terraform_path}}"
    state: present
    force_init: yes
  register: myregistered_grep_output

- name: Set host_ip
  include_tasks: roles/common/tasks/set_vars/host_ip.yml
  vars:
    myregistered_grep_output_var: "{{myregistered_grep_output}}"

##############start block######################
# # Uncomment to use ec2.py to fetch dynamic inventory
# - name: |
#     Ensure ec2.ini is used to get the ip address of the ec2 host.
#     To use, create a profile in your ./aws/creadentials file called 'prod'.
#     Add all necessary credentials
#   block:
#     - name: Install boto3
#       pip:
#         name: boto
#         executable: pip3

#     - name: Make ec.py file executable
#       file:
#         path: "{{playbook_dir}}/inventory/ec2.py"
#         mode: a+x

#     - name: Get dynamic inventory
#       command: "python3 {{playbook_dir}}/inventory/ec2.py --profile prod"
#       register: ec2_crunchify
############end block################
- name: Remove the host keys
  command: "ssh-keygen -R {{host_ip}}"

- name: Add the newly created EC2 instance(s) to the local host group
  blockinfile:
    marker: "#### {mark} ANSIBLE MANAGED BLOCK inventory ###"
    path: inventory/hosts
    block: |

            [webservers]
            {{host_ip}}

            [webservers:vars]
            ansible_connection=ssh
            ansible_ssh_common_args='-o IdentitiesOnly=yes -o StrictHostkeyChecking=no'
            ansible_ssh_private_key_file={{ssh_key_path}}.{{private_key_extension}}
            ansible_user=ubuntu
  delegate_to: 127.0.0.1

- name: Refresh inventory
  meta: refresh_inventory

- name: Set file permissions
  file:
    path: "{{ssh_key_path}}.{{private_key_extension}}"
    mode: '{{chmod_command}}'