---
- name: Get Terraform version
  shell: terraform --version
  register: terraform_version
  ignore_errors: true

########################
# Install Terraform
########################
- name: Ensure Terraform version > 0.12 is installed
  block:
  - name: Ensure gathering of facts
    setup:
    when: ansible_os_family is undefined

  - name: Debug ansible_distribution
    debug:
      msg: "ansible dist = {{ansible_distribution}} and secondly {{playbook_dir}}/group_vars/all/default_linux.yml"

  - name: Ensure os-based config variables are loaded
    include_vars: "{{ item }}"
    with_first_found:
      - "{{playbook_dir}}/group_vars/all/{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
      - "{{playbook_dir}}/group_vars/all/{{ansible_distribution}}.yml"
      - "{{playbook_dir}}/group_vars/all/default_linux.yml"

    # Ensure Terraform version > 0.12 is installed
  - import_tasks: roles/common/tasks/download_install.yml
    vars:
      module_package_url: "{{ terrafrom_download_link }}"
      module_package: "terraform"
  when: (terraform_version.stdout | regex_search('(\\d+\\.\\d+)') | float < 0.12 or terraform_version is search("command not found") )