---
# # Uncomment to setup redis for redis caching
# - import_tasks: setup_redis.yml

- import_tasks: create.yml
  when: infra_action is undefined or action == "create"

- import_tasks: delete.yml
  when: infra_action == "destroy"